### ISSUE TITLE
TODO: improvements PCB

### ISSUE THREAD

**Issue by JayWiz** [JayWiz/stmProgrammer#3]
add / change some stuff on PCB:

- [ ] mounting holes: if possible, 2 mounting holes (metric / M4)

- [ ] check Jumper JP6 (in case if there's no jumper, there are contacts on the backside of stlink)

- [ ] add some description to SJ1 and SJ2 on pcb

- [ ] change value of R1 and R2

**Comment by JayWiz** [comment]
- [ ] optional: connect drain of mosfets to pin header

**Comment by JayWiz** [comment]
- [ ] add testpoints

**Comment by JayWiz** [comment]
- [ ] add silkscreen printing
